-- ============================================================
-- Schéma PostgreSQL (Supabase) - Championnat France Pompiers Parapente
-- Converti depuis H2. Rejouable (CREATE TABLE IF NOT EXISTS).
-- ============================================================

-- Utilisateurs de l'application (comptes de connexion)
CREATE TABLE IF NOT EXISTS utilisateurs (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant     VARCHAR(100) NOT NULL UNIQUE,
    mot_de_passe    VARCHAR(256) NOT NULL,   -- haché SHA-256
    role            VARCHAR(40)  NOT NULL,   -- ADMINISTRATEUR, RESPONSABLE_EPREUVE, BENEVOLE, PILOTE, COMITE_PILOTES
    pilote_id       INT NULL,                -- si le compte est lié à un pilote
    actif           BOOLEAN NOT NULL DEFAULT TRUE
);

-- Pilotes (informations d'inscription au championnat)
CREATE TABLE IF NOT EXISTS pilotes (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_licence      VARCHAR(50) NOT NULL UNIQUE,
    nom                 VARCHAR(100) NOT NULL,
    prenom              VARCHAR(100) NOT NULL,
    caserne             VARCHAR(150),
    poids               DOUBLE PRECISION,
    email               VARCHAR(150),
    annee_naissance     INT,
    genre               VARCHAR(50),
    date_inscription    TIMESTAMPTZ DEFAULT now()
);

-- Épreuves (créées librement par le Responsable de l'épreuve)
CREATE TABLE IF NOT EXISTS epreuves (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                 VARCHAR(150) NOT NULL,
    description         VARCHAR(1000),
    mode_calcul         VARCHAR(20) NOT NULL DEFAULT 'FORMULE', -- FORMULE ou BAREME
    formule             VARCHAR(500),           -- utilisé si mode_calcul = FORMULE
    valeur_cle          VARCHAR(100),           -- utilisé si mode_calcul = BAREME
    sens_classement     VARCHAR(4) DEFAULT 'ASC', -- ASC (plus petit = meilleur) ou DESC (plus grand = meilleur)
    afficher_classement BOOLEAN NOT NULL DEFAULT TRUE,
    compte_dans_general BOOLEAN NOT NULL DEFAULT TRUE,
    actif               BOOLEAN NOT NULL DEFAULT TRUE,
    ordre               INT DEFAULT 0,
    date_creation       TIMESTAMPTZ DEFAULT now()
);

-- Paramètres/variables saisissables pour chaque épreuve
CREATE TABLE IF NOT EXISTS epreuve_parametres (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epreuve_id      INT NOT NULL,
    nom_variable    VARCHAR(60) NOT NULL,
    label           VARCHAR(150) NOT NULL,
    unite           VARCHAR(30),
    obligatoire     BOOLEAN DEFAULT TRUE,
    ordre           INT DEFAULT 0,
    FOREIGN KEY (epreuve_id) REFERENCES epreuves(id) ON DELETE CASCADE
);

-- Barème de points par rang (utilisé si mode_calcul = BAREME)
CREATE TABLE IF NOT EXISTS bareme_points (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epreuve_id  INT NOT NULL,
    rang        INT NOT NULL,
    points      DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (epreuve_id) REFERENCES epreuves(id) ON DELETE CASCADE,
    UNIQUE (epreuve_id, rang)
);

-- Inscription d'un pilote à une épreuve
CREATE TABLE IF NOT EXISTS inscriptions_epreuve (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pilote_id   INT NOT NULL,
    epreuve_id  INT NOT NULL,
    FOREIGN KEY (pilote_id) REFERENCES pilotes(id) ON DELETE CASCADE,
    FOREIGN KEY (epreuve_id) REFERENCES epreuves(id) ON DELETE CASCADE,
    UNIQUE (pilote_id, epreuve_id)
);

-- Résultats saisis (valeurs brutes + points calculés)
CREATE TABLE IF NOT EXISTS resultats (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epreuve_id      INT NOT NULL,
    pilote_id       INT NOT NULL,
    valeurs_json    VARCHAR(2000),   -- ex: {"temps": 812, "nbrBalises": 6}
    points          DOUBLE PRECISION DEFAULT 0,
    disqualifie     BOOLEAN DEFAULT FALSE,
    saisi_par       VARCHAR(100),
    date_saisie     TIMESTAMPTZ DEFAULT now(),
    FOREIGN KEY (epreuve_id) REFERENCES epreuves(id) ON DELETE CASCADE,
    FOREIGN KEY (pilote_id) REFERENCES pilotes(id) ON DELETE CASCADE,
    UNIQUE (epreuve_id, pilote_id)
);

-- Compte administrateur par défaut (identifiant: admin / mdp: admin123)
-- Remplace le "MERGE ... KEY(id)" de H2 par un upsert PostgreSQL
INSERT INTO utilisateurs (id, identifiant, mot_de_passe, role, actif)
VALUES (1, 'admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'ADMINISTRATEUR', TRUE)
ON CONFLICT (id) DO UPDATE
SET identifiant  = EXCLUDED.identifiant,
    mot_de_passe = EXCLUDED.mot_de_passe,
    role         = EXCLUDED.role,
    actif        = EXCLUDED.actif;

-- On a inséré id = 1 à la main : on resynchronise le compteur auto
-- pour que le prochain utilisateur ne reçoive pas un id déjà pris.
SELECT setval(
    pg_get_serial_sequence('utilisateurs', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM utilisateurs)
);

-- ------------------------------------------------------------
-- SÉCURITÉ SUPABASE : activer RLS sur toutes les tables.
-- Sans cela, les tables (dont les mots de passe hachés) sont
-- lisibles via l'API publique avec la clé "anon".
-- Une connexion JDBC avec l'utilisateur "postgres" contourne RLS,
-- donc ton application Java continue de fonctionner normalement.
-- ------------------------------------------------------------
ALTER TABLE utilisateurs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE pilotes              ENABLE ROW LEVEL SECURITY;
ALTER TABLE epreuves             ENABLE ROW LEVEL SECURITY;
ALTER TABLE epreuve_parametres   ENABLE ROW LEVEL SECURITY;
ALTER TABLE bareme_points        ENABLE ROW LEVEL SECURITY;
ALTER TABLE inscriptions_epreuve ENABLE ROW LEVEL SECURITY;
ALTER TABLE resultats            ENABLE ROW LEVEL SECURITY;
